# Generated by Django 4.2 on 2023-04-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_country_delete_countryrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
